receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    verbosity: detailed
  appdynamics:
    metrics:
      enabled: true
      url: http://otel-machineagent:8293/api/v1/metrics
      prefix: "Custom Metrics"
      rules:
        - description: cpu load average 1m
          matchConditions:
            - metricName: system.cpu.load_average.1m
          pathTemplate: 'HostMetrics|{{index .A "metricName"}}'
          aggregatorType: AVERAGE
        - description: teste robo fabricio
          matchConditions:
            - metricName: primeiro_contador
          pathTemplate: 'Robot|{{index .A "metricName"}}'
          aggregatorType: SUM
    analytics:
      enabled: false

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [appdynamics]

  telemetry:
    logs:
      level: debug
